screen = \
    [PIXEL_SHAPE] [RESOLUTION] \
    [DITHERING] [EFFECTS] \
    [OVERLAY] [IGNORES] \
    <empty> <empty> \
    <profile>
screen.columns = 2

screen.PIXEL_SHAPE = SQUARE_PIXELS PIXEL_ROUNDNESS GRID_GAP

screen.RESOLUTION = SAMPLING_MODE SAMPLE_STEP PIXEL_SIZE

screen.DITHERING = DITHER_MODE DITHER_STRENGTH

screen.EFFECTS = COLOR_LEVELS MONO_THRESHOLD CONTRAST SATURATION CRT_SCANLINES CRT_STRENGTH VIGNETTE VIGNETTE_STRENGTH

screen.OVERLAY = CLEAR_LINES LINE_THICKNESS

screen.IGNORES = IGNORE_HAND IGNORE_ENTITIES IGNORE_PARTICLES IGNORE_WATER IGNORE_TERRAIN IGNORE_SKY IGNORE_CLOUDS

sliders = PIXEL_SIZE SAMPLE_STEP DITHER_STRENGTH COLOR_LEVELS MONO_THRESHOLD PIXEL_ROUNDNESS GRID_GAP LINE_THICKNESS CONTRAST SATURATION CRT_STRENGTH VIGNETTE_STRENGTH

profile.DEFAULT = PIXEL_SIZE:256.0 SAMPLING_MODE:1 SAMPLE_STEP:6.0 DITHER_STRENGTH:1.0 COLOR_LEVELS:8.0 MONO_THRESHOLD:0.7 SQUARE_PIXELS:true PIXEL_ROUNDNESS:0.0 GRID_GAP:0.0 DITHER_MODE:0 CONTRAST:1.0 SATURATION:1.0 CRT_SCANLINES:false VIGNETTE:false IGNORE_HAND:false
profile.ROUND_MONOCHROME = PIXEL_SIZE:384.0 SAMPLING_MODE:0 SAMPLE_STEP:6.0 DITHER_STRENGTH:1.0 COLOR_LEVELS:-1.0 MONO_THRESHOLD:0.7 SQUARE_PIXELS:true PIXEL_ROUNDNESS:1.0 GRID_GAP:0.0 DITHER_MODE:0 CONTRAST:1.0 SATURATION:1.0 CRT_SCANLINES:false VIGNETTE:true VIGNETTE_STRENGTH:0.8 IGNORE_HAND:true
profile.PS1 = PIXEL_SIZE:128.0 SAMPLING_MODE:0 COLOR_LEVELS:256.0 DITHER_MODE:0 DITHER_STRENGTH:0.75 SQUARE_PIXELS:true PIXEL_ROUNDNESS:0.0 CONTRAST:1.2 SATURATION:1.1 CRT_SCANLINES:true CRT_STRENGTH:0.3 VIGNETTE:true VIGNETTE_STRENGTH:0.5 IGNORE_HAND:false
profile.GAMEBOY = PIXEL_SIZE:64.0 SAMPLING_MODE:0 COLOR_LEVELS:-1.0 MONO_THRESHOLD:0.8 DITHER_MODE:0 DITHER_STRENGTH:1.0 SQUARE_PIXELS:true PIXEL_ROUNDNESS:0.0 GRID_GAP:0.05 SATURATION:0.0 CRT_SCANLINES:false VIGNETTE:true VIGNETTE_STRENGTH:0.3 IGNORE_HAND:false
profile.RETRO_PC = PIXEL_SIZE:192.0 SAMPLING_MODE:1 SAMPLE_STEP:6.0 DITHER_STRENGTH:0.5 COLOR_LEVELS:32.0 SQUARE_PIXELS:true PIXEL_ROUNDNESS:0.0 GRID_GAP:0.0 CONTRAST:1.0 SATURATION:1.0 CRT_SCANLINES:true CRT_STRENGTH:0.15 VIGNETTE:false IGNORE_HAND:false
